### ISSUE TITLE
회의록이랑 총학소식 등등 게시글 정렬 수정

### ISSUE THREAD

**Issue by developerChans** [DKUcouncilhomepage/student-council-homepage-frontend#219]
기존 게시물에 한해서만 현재 정렬이 안된 것 일 수 있음 유의바람

**Comment by developerChans** [comment]
@won983212 

이거 혹시 response 역순으로 올 수 있나요? 페이지네이션부터요

**Comment by won983212** [comment]
요청보낼 때 query parameter로 sort에 createdAt, desc와 같이 지정하면 됩니다.
`?sort=createdAt,desc`

**Comment by developerChans** [comment]
@won983212 

![image](https://user-images.githubusercontent.com/68864422/230759876-072dc590-3f27-49b4-8fe1-a3ea6a160bf5.png)
url: `/post/conference?sort=date,desc&page=${Number(page) - 1}&size=6`,

page = 0, 1일때 null exception 발생

**Comment by developerChans** [comment]
회의록 totalElements 가 잘못 response로 오는 것 같음
![image](https://user-images.githubusercontent.com/68864422/230789634-6d5f3555-5edb-4d2d-af6e-7f3b6b55505a.png)

또한 desc를 넣었을경우 page를 지정시 page = 0에서 부터 에러가 발생함.
![image](https://user-images.githubusercontent.com/68864422/230789675-c8f50644-0f5f-4573-80d7-ae59d6b958d1.png)

**Comment by developerChans** [comment]
@won983212

**Comment by won983212** [comment]
백엔드 이슈인 듯 합니다.
