### ISSUE TITLE
자유게시판 사진 첨부 안됨

### ISSUE THREAD

**Issue by developerChans** [DKUcouncilhomepage/student-council-homepage-frontend#223]
제곧내

첨부시 여러장 가능하며, 단톡방에 고지된 용량 제한 지켜야함
또한, 확장자 검사를 통해 사진만 받아야함

**Comment by ho991217** [comment]
자유게시판에는 파일첨부 빼라며요...

**Comment by developerChans** [comment]
CORS 관련 문제인지는 자세히 모르겠음.

다만 다음 두사진은 local 환경에서의 모습임
![image](https://user-images.githubusercontent.com/68864422/230788300-d3685abf-c5cb-455d-a9f3-88207353f725.png)
![image](https://user-images.githubusercontent.com/68864422/230788309-2412edc0-0be5-4fe7-88bc-ba6151a8237f.png)

그러나 현재 merge된 repo에서 보면
![image](https://user-images.githubusercontent.com/68864422/230788325-68c5a314-cc70-4294-8db4-6cc0c0131c9c.png)
![image](https://user-images.githubusercontent.com/68864422/230788337-6fca812e-eb9e-41ac-8e0d-f1d9fa2496d9.png)

임

도와줘요 이현맨 호연맨
@won983212 @ho991217

**Comment by developerChans** [comment]
+ console log 지우기(메모용)
