### ISSUE TITLE
[REFACTOR] 비동기 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by ho991217** [DKUcouncilhomepage/student-council-homepage-frontend#273]
**Describe the new feature**
- 마감 기한: `null`
- 작업 내용: 비동기 랜더링 컴포넌트를 Suspense로 교체
- 관련 문서 또는 링크: `null`

**Todos**
- [ ] `Suspense` 컴포넌트로 교체

**Additional text**
-

**Comment by developerChans** [comment]
Refactoring 기간: ~05/28
